# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/audioout.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18src/proto/audioout.proto\x12\x1cviamlabs.service.audioout.v1\x1a\x1cgoogle/api/annotations.proto\"\x99\x01\n\x0bPlayRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n\tfile_path\x18\x02 \x01(\tR\x08\x66ilePath\x12\x1d\n\nloop_count\x18\x03 \x01(\x05R\tloopCount\x12\x1d\n\nmaxtime_ms\x18\x04 \x01(\x05R\tmaxtimeMs\x12\x1b\n\tfadein_ms\x18\x05 \x01(\x05R\x08\x66\x61\x64\x65inMs\"\"\n\x0cPlayResponse\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\"!\n\x0bStopRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"\"\n\x0cStopResponse\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text2\xb3\x02\n\x0f\x41udiooutService\x12\x8e\x01\n\x04Play\x12).viamlabs.service.audioout.v1.PlayRequest\x1a*.viamlabs.service.audioout.v1.PlayResponse\"/\x82\xd3\xe4\x93\x02)\"\'/acme/api/v1/service/speech/{name}/play\x12\x8e\x01\n\x04Stop\x12).viamlabs.service.audioout.v1.StopRequest\x1a*.viamlabs.service.audioout.v1.StopResponse\"/\x82\xd3\xe4\x93\x02)\"\'/acme/api/v1/service/speech/{name}/stopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.audioout_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOOUTSERVICE.methods_by_name['Play']._options = None
  _AUDIOOUTSERVICE.methods_by_name['Play']._serialized_options = b'\202\323\344\223\002)\"\'/acme/api/v1/service/speech/{name}/play'
  _AUDIOOUTSERVICE.methods_by_name['Stop']._options = None
  _AUDIOOUTSERVICE.methods_by_name['Stop']._serialized_options = b'\202\323\344\223\002)\"\'/acme/api/v1/service/speech/{name}/stop'
  _globals['_PLAYREQUEST']._serialized_start=89
  _globals['_PLAYREQUEST']._serialized_end=242
  _globals['_PLAYRESPONSE']._serialized_start=244
  _globals['_PLAYRESPONSE']._serialized_end=278
  _globals['_STOPREQUEST']._serialized_start=280
  _globals['_STOPREQUEST']._serialized_end=313
  _globals['_STOPRESPONSE']._serialized_start=315
  _globals['_STOPRESPONSE']._serialized_end=349
  _globals['_AUDIOOUTSERVICE']._serialized_start=352
  _globals['_AUDIOOUTSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
